noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
number = input("Enter a number: ")
verb2 = input("Enter 2nd verb: ")
noun2 = input("Enter 2nd noun: ")
verb3 = input("Enter 3rd verb: ")
adverb1 = input("Enter an adverb: ")
verb4 = input("Enter 4th verb: ")
verb5 = input("Enter 5th verb: ")
verb6 = input("Enter 6th verb: ")
verb7 = input("Enter 7th verb: ")
noun3 = input("Enter 3rd noun: ")
verb8 = input("Enter 8th verb: ")
verb9 = input("Enter 9th verb: ")
celebrity = input("Enter a celebrity's name: ")
noun4 = input("Enter 4th noun: ")
adjective1 = input("Enter an adjective: ")
verb10 = input("Enter 10th verb: ")
noun5 = input("Enter 5th noun: ")
verb12 = input("Enter 12th verb: ")
noun6 = input("Enter 6th noun: ")
noun7 = input("Enter 7th noun: ")
verb13 = input("Enter 13th verb: ")

madlib = f"While Emily was in the {noun1}, she {verb1} a group of around {number} people {verb2} to the {noun2}. She heard people {verb3} {adverb1} before {verb4} someone who looked familiar being {verb5} by a lot of people. She {verb6} the person and {verb7} them into the {noun3}. She {verb8} at the person before finally {verb9} who it was. It was {celebrity}, a famous {noun4}. She {verb8} at the person {adjective1}, before {verb10} out the {noun5}. After {verb8} everyone was gone, she {verb12} her {noun6} and {noun7} to the person before {verb13}."

print(madlib)